ls ../TomtomOutputHumanMouse/TomtomOut_*/*.txt > ../TomtomOutputHumanMouse/TomtomOutFileNames
ls ../TomtomOutputHumanMouseIC025/TomtomOut_*/*.txt > ../TomtomOutputHumanMouseIC025/TomtomOutFileNames
ls ../TomtomOutputHumanMouseIC05/TomtomOut_*/*.txt > ../TomtomOutputHumanMouseIC05/TomtomOutFileNames
ls ../TomtomOutputHumanMouseIC1/TomtomOut_*/*.txt > ../TomtomOutputHumanMouseIC1/TomtomOutFileNames
ls ../TomtomOutputHumanMouseEd/TomtomOut_*/*.txt > ../TomtomOutputHumanMouseEd/TomtomOutFileNames
ls ../TomtomOutputHumanMouseIC025Ed/TomtomOut_*/*.txt > ../TomtomOutputHumanMouseIC025Ed/TomtomOutFileNames
ls ../TomtomOutputHumanMouseIC05Ed/TomtomOut_*/*.txt > ../TomtomOutputHumanMouseIC05Ed/TomtomOutFileNames
ls ../TomtomOutputHumanMouseIC1Ed/TomtomOut_*/*.txt > ../TomtomOutputHumanMouseIC1Ed/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophila/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophila/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophilaIC025/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophilaIC025/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophilaIC05/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophilaIC05/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophilaIC1/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophilaIC1/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophilaEd/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophilaEd/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophilaIC025Ed/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophilaIC025Ed/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophilaIC05Ed/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophilaIC05Ed/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophilaIC1Ed/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophilaIC1Ed/TomtomOutFileNames
python getTFMotifDists.py ../TomtomOutputHumanMouse/TomtomOutFileNames ../TomtomOutputHumanMouse/TomtomOutBestDistsHumanMouse
python getTFMotifDists.py ../TomtomOutputHumanMouseIC025/TomtomOutFileNames ../TomtomOutputHumanMouseIC025/TomtomOutBestDistsHumanMouseIC025
python getTFMotifDists.py ../TomtomOutputHumanMouseIC05/TomtomOutFileNames ../TomtomOutputHumanMouseIC05/TomtomOutBestDistsHumanMouseIC05
python getTFMotifDists.py ../TomtomOutputHumanMouseIC1/TomtomOutFileNames ../TomtomOutputHumanMouseIC1/TomtomOutBestDistsHumanMouseIC1
python getTFMotifDists.py ../TomtomOutputHumanMouseEd/TomtomOutFileNames ../TomtomOutputHumanMouseEd/TomtomOutBestDistsHumanMouseEd
python getTFMotifDists.py ../TomtomOutputHumanMouseIC025Ed/TomtomOutFileNames ../TomtomOutputHumanMouseIC025Ed/TomtomOutBestDistsHumanMouseIC025Ed
python getTFMotifDists.py ../TomtomOutputHumanMouseIC05Ed/TomtomOutFileNames ../TomtomOutputHumanMouseIC05Ed/TomtomOutBestDistsHumanMouseIC05Ed
python getTFMotifDists.py ../TomtomOutputHumanMouseIC1Ed/TomtomOutFileNames ../TomtomOutputHumanMouseIC1Ed/TomtomOutBestDistsHumanMouseIC1Ed
python getTFMotifDists.py ../TomtomOutputHumanDrosophila/TomtomOutFileNames ../TomtomOutputHumanDrosophila/TomtomOutBestDistsHumanDrosophila
python getTFMotifDists.py ../TomtomOutputHumanDrosophilaIC025/TomtomOutFileNames ../TomtomOutputHumanDrosophilaIC025/TomtomOutBestDistsHumanDrosophilaIC025
python getTFMotifDists.py ../TomtomOutputHumanDrosophilaIC05/TomtomOutFileNames ../TomtomOutputHumanDrosophilaIC05/TomtomOutBestDistsHumanDrosophilaIC05
python getTFMotifDists.py ../TomtomOutputHumanDrosophilaIC1/TomtomOutFileNames ../TomtomOutputHumanDrosophilaIC1/TomtomOutBestDistsHumanDrosophilaIC1
python getTFMotifDists.py ../TomtomOutputHumanDrosophilaEd/TomtomOutFileNames ../TomtomOutputHumanDrosophilaEd/TomtomOutBestDistsHumanDrosophilaEd
python getTFMotifDists.py ../TomtomOutputHumanDrosophilaIC025Ed/TomtomOutFileNames ../TomtomOutputHumanDrosophilaIC025Ed/TomtomOutBestDistsHumanDrosophilaIC025Ed
python getTFMotifDists.py ../TomtomOutputHumanDrosophilaIC05Ed/TomtomOutFileNames ../TomtomOutputHumanDrosophilaIC05Ed/TomtomOutBestDistsHumanDrosophilaIC05Ed
python getTFMotifDists.py ../TomtomOutputHumanDrosophilaIC1Ed/TomtomOutFileNames ../TomtomOutputHumanDrosophilaIC1Ed/TomtomOutBestDistsHumanDrosophilaIC1Ed

ls ../TomtomOutputHumanMouseKullback/TomtomOut_*/*.txt > ../TomtomOutputHumanMouseKullback/TomtomOutFileNames
ls ../TomtomOutputHumanMouseIC1Kullback/TomtomOut_*/*.txt > ../TomtomOutputHumanMouseIC1Kullback/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophilaKullback/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophilaKullback/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophilaIC1Kullback/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophilaIC1Kullback/TomtomOutFileNames
python getTFMotifDists.py ../TomtomOutputHumanMouseKullback/TomtomOutFileNames ../TomtomOutputHumanMouseKullback/TomtomOutBestDistsHumanMouseKullback
python getTFMotifDists.py ../TomtomOutputHumanMouseIC1Kullback/TomtomOutFileNames ../TomtomOutputHumanMouseIC1Kullback/TomtomOutBestDistsHumanMouseIC1Kullback
python getTFMotifDists.py ../TomtomOutputHumanDrosophilaKullback/TomtomOutFileNames ../TomtomOutputHumanDrosophilaKullback/TomtomOutBestDistsHumanDrosophilaKullback
python getTFMotifDists.py ../TomtomOutputHumanDrosophilaIC1Kullback/TomtomOutFileNames ../TomtomOutputHumanDrosophilaIC1Kullback/TomtomOutBestDistsHumanDrosophilaIC1Kullback

ls ../TomtomOutputHumanMouseSandelin/TomtomOut_*/*.txt > ../TomtomOutputHumanMouseSandelin/TomtomOutFileNames
ls ../TomtomOutputHumanMouseIC1Sandelin/TomtomOut_*/*.txt > ../TomtomOutputHumanMouseIC1Sandelin/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophilaSandelin/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophilaSandelin/TomtomOutFileNames
ls ../TomtomOutputHumanDrosophilaIC1Sandelin/TomtomOut_*/*.txt > ../TomtomOutputHumanDrosophilaIC1Sandelin/TomtomOutFileNames
python getTFMotifDists.py ../TomtomOutputHumanMouseSandelin/TomtomOutFileNames ../TomtomOutputHumanMouseSandelin/TomtomOutBestDistsHumanMouseSandelin
python getTFMotifDists.py ../TomtomOutputHumanMouseIC1Sandelin/TomtomOutFileNames ../TomtomOutputHumanMouseIC1Sandelin/TomtomOutBestDistsHumanMouseIC1Sandelin
python getTFMotifDists.py ../TomtomOutputHumanDrosophilaSandelin/TomtomOutFileNames ../TomtomOutputHumanDrosophilaSandelin/TomtomOutBestDistsHumanDrosophilaSandelin
python getTFMotifDists.py ../TomtomOutputHumanDrosophilaIC1Sandelin/TomtomOutFileNames ../TomtomOutputHumanDrosophilaIC1Sandelin/TomtomOutBestDistsHumanDrosophilaIC1Sandelin
